name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: MuhammadHaseebUlHaqq/readme_maker_for_github
